#!/bin/sh

set -e # If anything fails, stop the script.
set -u # If an undefined variable is expanded, stop the script.

ROOT=$(git rev-parse --show-toplevel)

cd "${ROOT}"

# Uses only every nth frame to save space.
convert -verbose -resize 415x -loop 0 -delay 1x60 $(ls -1 src/*.png | awk 'NR == 1 || NR % 4 == 0') preview.gif
mogrify -layers 'optimize' -fuzz 2% preview.gif
