#!/bin/sh

set -e # If anything fails, stop the script.
set -u # If an undefined variable is expanded, stop the script.

if [ "${#}" -lt 1 ]; then
  echo "Usage: ${0} [patch|minor|major]"
  exit 1
fi

ROOT=$(git rev-parse --show-toplevel)
VERSION_TYPE="${1}"

cd "${ROOT}"

for size in 1024x 768x 480x; do
  mkdir -p "dist/${size}"
  parallel --verbose convert -resize "${size}" -quality 100 {} "dist/${size}/{/.}.png" ::: src/*.png
  imageoptim "dist/${size}"
done

npm version "${VERSION_TYPE}"

version=$(git log --pretty=format:%s | head -n 1)
filename="discard-tray-photos-${version}.zip"

zip -r "${filename}" dist/*
gh release create ${version} --title ${version} --notes '' "${filename}"
rm "${filename}"
